// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnIHYRxzBtwxSXfK7QvRE_uZ4twdX61hU',
    appId: '1:993690159807:web:9545a79079bcf34f1c940a',
    messagingSenderId: '993690159807',
    projectId: 'studyflow-d5d44',
    authDomain: 'studyflow-d5d44.firebaseapp.com',
    storageBucket: 'studyflow-d5d44.firebasestorage.app',
    measurementId: 'G-S58TVJPZ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04PdFjDUCmmq04tC80-z52h_qOuQ5amU',
    appId: '1:993690159807:android:b36c209e7428b3091c940a',
    messagingSenderId: '993690159807',
    projectId: 'studyflow-d5d44',
    storageBucket: 'studyflow-d5d44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCqapm0UjYGfhRi_K1vIUNOYvFWF61-do',
    appId: '1:993690159807:ios:5bf123c884bbf3611c940a',
    messagingSenderId: '993690159807',
    projectId: 'studyflow-d5d44',
    storageBucket: 'studyflow-d5d44.firebasestorage.app',
    iosBundleId: 'com.example.studyflowFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCqapm0UjYGfhRi_K1vIUNOYvFWF61-do',
    appId: '1:993690159807:ios:5bf123c884bbf3611c940a',
    messagingSenderId: '993690159807',
    projectId: 'studyflow-d5d44',
    storageBucket: 'studyflow-d5d44.firebasestorage.app',
    iosBundleId: 'com.example.studyflowFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnIHYRxzBtwxSXfK7QvRE_uZ4twdX61hU',
    appId: '1:993690159807:web:3ba0f45646ee30161c940a',
    messagingSenderId: '993690159807',
    projectId: 'studyflow-d5d44',
    authDomain: 'studyflow-d5d44.firebaseapp.com',
    storageBucket: 'studyflow-d5d44.firebasestorage.app',
    measurementId: 'G-YSP9K7MTBT',
  );
}
